apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: zenxbattle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lijuthomas/zenx2-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          value: "http://zenxbattle.local"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: zenxbattle
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
