7337
apiVersion: v1
kind: ConfigMap
metadata:
  name: xcode-config
  namespace: xcode
data:
  ENVIRONMENT: "production"
  APIGATEWAYPORT: "7000"
  FRONTENDURL: "http://xcode.local"
  APPURL: "http://xcode.local"
  USERGRPCURL: "auth-user-service:50051"
  PROBLEMGRPCURL: "problems-service:50055"
  CHALLENGEGRPCSERVICEPORT: "50057"
  CHALLENGEGRPCURL: "challenge-manager:50057"
  NATSURL: "nats://nats:4222"
  REDISURL: "redis:6379"
  MONGODBURL: "mongodb://mongo:27017"
  POSTGRESDSN: "host=postgres port=5432 user=admin password=password dbname=xcode sslmode=disable"
  PSQLURL: "host=postgres port=5432 user=admin password=password dbname=xcode sslmode=disable"
  MONGOURL: "mongodb://mongo:27017"
  SESSIONSECRETKEY: "xcode-session-secret-k3s"
  APIGATEWAYTOKENCHECKURL: "http://api-gateway:7000/api/v1/users/check-token"
  RATE_LIMIT: "5"
  RATE_LIMIT_BURST: "15"
  MAX_WORKERS: "1"
  JOB_COUNT: "10"
  GOOGLECLIENTID: ""
  GOOGLECLIENTSECRET: ""
  GOOGLEREDIRECTURL: ""
  SMTPHOST: ""
  SMTPPORT: "587"
  SMTPUSER: ""
  SMTPAPPKEY: ""
  RESENDAPIKEY: ""
  BETTERSTACKSOURCETOKEN: ""
  BETTERSTACKUPLOADURL: ""
