server {
    listen 8082;
    server_name xcode.local _;

    location /api {
        proxy_pass http://10.43.248.246:7000;
        proxy_set_header Host $host;
    }

    location /grafana {
        proxy_pass http://10.43.206.37:3000;
        proxy_set_header Host $host;
    }

    location /metrics {
        proxy_pass http://10.43.220.162:9090;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://10.43.47.95:80;
        proxy_set_header Host $host;
    }
}
