apiVersion: v1
kind: Secret
metadata:
  name: zenxbattle-secrets
  namespace: zenxbattle
type: Opaque
stringData:
  JWTSECRETKEY: "zenxbattle-jwt-secret-onprem"
  ADMINUSERNAME: "admin"
  ADMINPASSWORD: "admin"
  POSTGRES_PASSWORD: "password"
  MONGO_INITDB_ROOT_PASSWORD: "password"
