apiVersion: v1
kind: Secret
metadata:
  name: xcode-secrets
  namespace: xcode
type: Opaque
stringData:
  JWTSECRETKEY: "xcode-jwt-secret-onprem"
  ADMINUSERNAME: "admin"
  ADMINPASSWORD: "admin"
  POSTGRES_PASSWORD: "password"
  MONGO_INITDB_ROOT_PASSWORD: "password"
