apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: xcode
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: xcode
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: xcode
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
